name: web_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  args: ^2.3.0
  dart_jsonwebtoken: ^2.7.1
  envied: ^0.3.0+3
  mysql1: ^0.20.0
  shelf: ^1.4.0
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.0
  xml: ^6.2.2

dev_dependencies:
  build_runner: ^2.4.5
  envied_generator: ^0.3.0+3
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
